"""added funnel stage fixed

Revision ID: eeb7ba3a978a
Revises: e6ddcfcf0e97
Create Date: 2026-04-25 19:37:47.546550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb7ba3a978a'
down_revision: Union[str, Sequence[str], None] = 'e6ddcfcf0e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
